### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by citrixrep** [hoffstadt/SimpleDataFlow#1]
**Describe the bug**
segmentation fault with last version of DearPyGui 

OS: Kali linux
python: Python 3.9.2

**Comment by hoffstadt** [comment]
Yep. This need to be updated for 1.0. Will do so soon.

**Comment by citrixrep** [comment]
thanks ;)

**Comment by insecureworld** [comment]
i have same issue :(

**Comment by hoffstadt** [comment]
Just updated for 1.x.

Not a fan of my coding when I made this, so forgive the messiness!
